const timeCatalog = [
    { value: "1 AÑO", label: "1 AÑO" },
    { value: "2 AÑOS", label: "2 AÑOS" },
    { value: "3 AÑOS", label: "3 AÑOS" },
    { value: "4 AÑOS", label: "4 AÑOS" },
    { value: "5 AÑOS", label: "5 AÑOS" },
    { value: "6 AÑOS", label: "6 AÑOS" },
    { value: "7 AÑOS", label: "7 AÑOS" },
    { value: "8 AÑOS", label: "8 AÑOS" },
    { value: "9 AÑOS", label: "9 AÑOS" },
    { value: "10 AÑOS", label: "10 AÑOS" },
    { value: "11 AÑOS", label: "11 AÑOS" },
    { value: "12 AÑOS", label: "12 AÑOS" },
    { value: "13 AÑOS", label: "13 AÑOS" },
    { value: "14 AÑOS", label: "14 AÑOS" },
    { value: "15 AÑOS", label: "15 AÑOS" },
    { value: "16 AÑOS", label: "16 AÑOS" },
    { value: "17 AÑOS", label: "17 AÑOS" },
    { value: "18 AÑOS", label: "18 AÑOS" },
    { value: "19 AÑOS", label: "19 AÑOS" },
    { value: "20 AÑOS", label: "20 AÑOS" },
    { value: "21 AÑOS", label: "21 AÑOS" },
    { value: "22 AÑOS", label: "22 AÑOS" },
    { value: "23 AÑOS", label: "23 AÑOS" },
    { value: "24 AÑOS", label: "24 AÑOS" },
    { value: "25 AÑOS", label: "25 AÑOS" },
    { value: "26 AÑOS", label: "26 AÑOS" },
    { value: "27 AÑOS", label: "27 AÑOS" },
    { value: "28 AÑOS", label: "28 AÑOS" },
    { value: "29 AÑOS", label: "29 AÑOS" },
    { value: "30 AÑOS", label: "30 AÑOS" },
  ];
  
  export default timeCatalog;
  