const dataReinversion = [
    {
      Tasa: "10.06%",
      Plazo: "7 días",
      Rendimiento: "",
      key: 7,
      gatR: "6.68%",
      gatN: "10.70%",
      ClassName: `row seven`,
      Size: "7.4",
    },
    {
      Tasa: "10.30%",
      Plazo: "30 días",
      Rendimiento: "",
      key: 30,
      gatR: "6.79%",
      gatN: "10.80%",
      ClassName: `row twenty-eight`,
      Size: "15.6",
    },
    {
      Tasa: "10.95% ",
      Plazo: "90 días",
      Rendimiento: "",
      key: 90,
      gatR: "7.37%",
      gatN: "11.41%",
      ClassName: `row ninety`,
      Size: "23.7",
    },
    {
      Tasa: "11.18% ",
      Plazo: "180 días",
      Rendimiento: "",
      key: 180,
      gatR: "7.45%",
      gatN: "11.49%",
      ClassName: `row three-sixty-five`,
      Size: "32",
    },
    {
      Tasa: "13.59%",
      Plazo: "360 días",
      Rendimiento: "",
      key: 360,
      morePopular: false,
      gatR: "9.47%",
      gatN: "13.59%",
      ClassName: `row three-sixty-six`,
      Size: "40",
    },

    {
      Tasa: "8.00%",
      Plazo: "540 días",
      Rendimiento: "",
      key: 540,
      gatR: "4.09%",
      gatN: "8.00%",
      ClassName: `row three-sixty-nine`,
      Size: "48.2",
    },

    {
      Tasa: "12.09%",
      Plazo: "720 días",
      Rendimiento: "",
      key: 720,
      gatR: "8.03%",
      gatN: "12.09%",
      ClassName: `row three-sixty-seven`,
      Size: "56.5",
    },
    {
      Tasa: "11.25%",
      Plazo: "1,080 días",
      Rendimiento: "",
      key: 1080,
      gatR: "7.22%",
      gatN: "11.25%",
      ClassName: `row three-sixty-eight`,
      Size: "64.6",
    },
    {
      Tasa: "10.25%",
      Plazo: "1,440 días",
      Rendimiento: "",
      key: 1440,
      gatR: "6.25%",
      gatN: "10.25%",
      ClassName: `row three-sixty-nine`,
      Size: "72.7",
    },
    {
      Tasa: "9.75%",
      Plazo: "1,800 días",
      Rendimiento: "",
      key: 1800,
      gatR: "5.77%",
      gatN: "9.75%",
      ClassName: "row three-sixty-ten",
      Size: "81",
    },


   
  ];
  
  export default dataReinversion;