const dataReinversion = [
    {
      Tasa: "10.06%",
      Plazo: "7 dias",
      Rendimiento: "",
      key: 7,
      gatR: "6.56%",
      gatN: "10.70%",
      ClassName: `row seven`,
      Size: "8.5",
    },
    {
      Tasa: "11.09%",
      Plazo: "1 mes",
      Rendimiento: "",
      key: 30,
      gatR: "7.50%",
      gatN: "11.67%",
      ClassName: `row twenty-eight`,
      Size: "17",
    },
    {
      Tasa: "12.09% ",
      Plazo: "3 meses",
      Rendimiento: "",
      key: 90,
      gatR: "8.44%",
      gatN: "12.65%",
      ClassName: `row ninety`,
      Size: "25.5",
    },
    {
      Tasa: "12.29% ",
      Plazo: "6 meses",
      Rendimiento: "",
      key: 180,
      gatR: "8.46%",
      gatN: "12.67%",
      ClassName: `row three-sixty-five`,
      Size: "34",
    },
    {
      Tasa: "14.09%",
      Plazo: "12 meses",
      Rendimiento: "",
      key: 360,
      morePopular: false,
      gatR: "9.83%",
      gatN: "14.09%",
      ClassName: `row three-sixty-six`,
      Size: "42.6",
    },
    {
      Tasa: "14.55%",
      Plazo: "2 años",
      Rendimiento: "",
      key: 720,
      gatR: "10.27%",
      gatN: "14.55%",
      ClassName: `row three-sixty-seven`,
      Size: "51.1",
    },
    {
      Tasa: "15.01%",
      Plazo: "3 años",
      Rendimiento: "",
      key: 1080,
      gatR: "10.71%",
      gatN: "15.01%",
      ClassName: `row three-sixty-eight`,
      Size: "59.6",
    },
    {
      Tasa: "13.25%",
      Plazo: "4 años",
      Rendimiento: "",
      key: 1440,
      gatR: "9.02%",
      gatN: "13.25%",
      ClassName: `row three-sixty-nine`,
      Size: "68.1",
    },
    {
      Tasa: "12.75%",
      Plazo: "5 años",
      Rendimiento: "",
      key: 1800,
      gatR: "8.54%",
      gatN: "12.75%",
      ClassName: "row three-sixty-ten",
      Size: "76.6",
    },
  ];
  
  export default dataReinversion;